/**
 * Static image imports.
 *
 * Next ships these declarations in `next-env.d.ts` — but that file is
 * **generated by `next build` and gitignored**, and CI runs `pnpm typecheck`
 * *before* `pnpm build`. Relying on it therefore typechecks on a developer's
 * machine (where an earlier build left the file behind) and fails in CI, which
 * is exactly the false pass it produced the first time. Declaring what we
 * actually use, in a committed file, removes the ordering dependency.
 *
 * Only PNG, because that is all the guide's figures are.
 */

declare module '*.png' {
  const content: import('next/image').StaticImageData;
  export default content;
}
